name: Build site

on:
  workflow_dispatch:
  push:
    paths:
    - 'source/**/*'
    - '.github/workflows/build-site.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installs
      run: |
        sudo pip3 install markdown
    - name: Build site
      run: |
        find content -name '*.html' -delete # Ensure deletions are picked up
        cd source
        python3 generate.py
        cd ..
        git config --global user.email "dev@ponymail.apache.org"
        git config --global user.name "Ponymail PPMC"
        git status
        git add content
        if git commit -m "Commit build products"
        then
          git push
        else
          echo "No change"
          true # ensure step is successful
        fi
